CREATE TABLE users (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    display VARCHAR(255) NOT NULL,
    dob DATE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE income( 
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
    user_id INT NOT NULL, 
    amount DECIMAL(10,2) NOT NULL, 
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP, 
    FOREIGN KEY (user_id) REFERENCEs users(id)
);
